### ISSUE TITLE
Seems to not work with Traefik 3.3.1

### ISSUE THREAD

**Issue by keriati** [JonasSchubert/traefik-block-paths#34]
Sadly it seems to not work with Traefik 3.3.1

in treafik.yml:

```yml
experimental:
  plugins:
    block-paths:
      moduleName: github.com/JonasSchubert/traefik-block-paths
      version: "v0.1.1"
```

in config.yml:

```yml
http:
  middlewares:
    block-metrics:
      plugin:
        block-paths:
          allowLocalRequests: true
          regex:
            - "^/metrics(.*)"
          statusCode: 403
```

when the middleware is applied, the /metrics path seems to still be accessible.
